### ISSUE TITLE
The model does not use symbolic links for subfolders in performance calculations

### ISSUE THREAD

**Issue by 919607** [deepmodeling/APEX#81]
Dear APEX developers: 
    I found during the use of APEX that DPMD's model did not create symbolic link, but copied each model and placed it in a subfolders for computation. For example, graph-compress.pb in the following relaxation folder.

├── in.lammps
└── relax_task
    ├── conf.lmp
    ├── CONTCAR
    ├── dump.relax
    ├── graph-compress.pb
    ├── in.lammps
    ├── inter.json
    ├── log.lammps
    ├── POSCAR
    ├── result.json
    ├── structure.json
    └── task.json

Name: apex-flow
Version: 1.2.5

**Comment by ZLI-afk** [comment]
> Dear APEX developers: I found during the use of APEX that DPMD's model did not create symbolic link, but copied each model and placed it in a subfolders for computation. For example, graph-compress.pb in the following relaxation folder.
> 
> ├── in.lammps └── relax_task ├── conf.lmp ├── CONTCAR ├── dump.relax ├── graph-compress.pb ├── in.lammps ├── inter.json ├── log.lammps ├── POSCAR ├── result.json ├── structure.json └── task.json
> 
> Name: apex-flow Version: 1.2.5

Were you using the `submit` or the `do` sub-command to create the tasks? If `submit`, it is expected to copy the potential files to each subfolders.

**Comment by 919607** [comment]
Okay, thank you. I understand. I used the `submit` command.
