### ISSUE TITLE
How to run Apex correctly

### ISSUE THREAD

**Issue by jscdefk** [deepmodeling/APEX#9]
I use Apex（LAMMPS） for relaxation, and the command line is as follows: apex param_relax.json
![image](https://github.com/deepmodeling/APEX/assets/114908920/364faa03-a71c-42bb-a35a-c6d07b46fd8e)
The following error occurred:urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=9000): Max retries exceeded with url: /my-bucket?location= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f862c0cd150>: Failed to establish a new connection: [Errno 111] Connection refused'))
May I ask how to handle errors and whether the input is missing anything

**Comment by ZLI-afk** [comment]
As it was trying to connect local host of 127.0.0.1, you may double check if your local `dflow` environment has been setup and port forwarded properly. Please refer to [dflow repo](https://github.com/deepmodeling/dflow) for detail installation guide.

**Comment by jscdefk** [comment]
thank   you



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 07/05/2023 21:07 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [deepmodeling/APEX] How to run Apex correctly (Issue #9) |

As it was trying to connect local host of 127.0.0.1, you may double check if your local dflow environment has been setup and port forwarded properly. Please refer to dflow repo for detail installation guide.
